version: '2'
services:
  test:
    build: .
    volumes:
      - .:/usr/src/app
      - ${HOME}/.aws:/root/.aws
    environment:
      S3_BUCKET: "youtube-farming"
    working_dir: "/usr/src/app"
    entrypoint: "/usr/src/app/node_modules/nodemon/bin/nodemon.js -L --ignore node_modules/ --ignore public/ --ignore .tmp/ index.js"
