version: '2'
services:
  youtuber:
    build: .
    volumes:
      - .:/usr/src/app
    working_dir: "/usr/src/app"
    entrypoint: "/usr/src/app/node_modules/nodemon/bin/nodemon.js -L --ignore node_modules/ --ignore public/ --ignore .tmp/ index.js"
